import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const {
      restaurantName,
      cuisineType,
      dishName,
      originalPrice,
      promoPrice,
      discount,
      targetAudience,
      brandTone,
      campaignDay,
      objective,
      referenceImage,
    } = await req.json();

    const promptText = `Create a professional Instagram promotional post image for a restaurant.

RESTAURANT: "${restaurantName}" — ${cuisineType} cuisine.
DISH: "${dishName}"
PROMOTION: From R$${originalPrice} to R$${promoPrice} (${discount}% OFF)
DAY: ${campaignDay}
TARGET: ${targetAudience}
TONE: ${brandTone}
OBJECTIVE: ${objective}

DESIGN REQUIREMENTS:
- Professional food photography style with the dish as hero element
- Bold headline text overlaid: "${dishName}"
- Prominent price display: crossed out "R$${originalPrice}" and highlighted "R$${promoPrice}"
- A circular discount badge showing "${discount}% OFF"
- Restaurant name "${restaurantName}" at bottom
- Warm, appetizing color palette with rich contrast
- Instagram square format (1:1 aspect ratio)
- Premium, magazine-quality look
- No blurry text — all text must be sharp and readable
- Dark or blurred background to make the dish pop
${referenceImage ? "\nIMPORTANT: Use the attached reference image as the base/inspiration for the dish photo. Keep the food from the reference photo but enhance it with professional lighting, add the promotional text overlay, discount badge, and restaurant branding on top of it." : ""}

DO NOT include any watermarks or logos other than the restaurant name.`;

    console.log("Generating promo image for:", dishName, "at", restaurantName, "with reference:", !!referenceImage);

    // Build message content — text only or multimodal with reference image
    const userContent: any = referenceImage
      ? [
          { type: "text", text: promptText },
          { type: "image_url", image_url: { url: referenceImage } },
        ]
      : promptText;

    const response = await fetch(
      "https://ai.gateway.lovable.dev/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash-image",
          messages: [{ role: "user", content: userContent }],
          modalities: ["image", "text"],
        }),
      }
    );

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Limite de requisições excedido. Tente novamente em alguns segundos." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Créditos de IA insuficientes. Adicione créditos ao workspace." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const errorText = await response.text();
      console.error("AI gateway error:", response.status, errorText);
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    const imageUrl =
      data.choices?.[0]?.message?.images?.[0]?.image_url?.url || null;
    const textResponse = data.choices?.[0]?.message?.content || "";

    if (!imageUrl) {
      throw new Error("No image was generated by the AI model");
    }

    return new Response(
      JSON.stringify({ imageUrl, textResponse }),
      {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    console.error("generate-promo-image error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(
      JSON.stringify({ error: message }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
